`timescale 1ns/1ps

module vmem_dat_arb_test_top (
    input wire clk,
    input wire resetn,
    input wire return_valid,
    output wire return_ready,
    input wire [3:0] return_slice,
    input wire [1:0] return_dma,
    input wire [31:0] return_data,
    input wire order_valid,
    output wire order_ready,
    input wire [1:0] order_dma,
    input wire [3:0] order_slice,
    output wire [3:0] out_valid,
    input wire [3:0] out_ready,
    output wire [127:0] out_data
);
    wire [15:0] in_ready;
    wire [3:0] dma_order_ready;

    assign return_ready = in_ready[return_slice];
    assign order_ready = dma_order_ready[order_dma];

    VmemDatArbOut1_1 dut (
        .io_in_data_0_valid(return_valid && return_slice == 0),
        .io_in_data_0_ready(in_ready[0]),
        .io_in_data_0_payload({return_dma, return_data}),
        .io_in_data_1_valid(return_valid && return_slice == 1),
        .io_in_data_1_ready(in_ready[1]),
        .io_in_data_1_payload({return_dma, return_data}),
        .io_in_data_2_valid(return_valid && return_slice == 2),
        .io_in_data_2_ready(in_ready[2]),
        .io_in_data_2_payload({return_dma, return_data}),
        .io_in_data_3_valid(return_valid && return_slice == 3),
        .io_in_data_3_ready(in_ready[3]),
        .io_in_data_3_payload({return_dma, return_data}),
        .io_in_data_4_valid(return_valid && return_slice == 4),
        .io_in_data_4_ready(in_ready[4]),
        .io_in_data_4_payload({return_dma, return_data}),
        .io_in_data_5_valid(return_valid && return_slice == 5),
        .io_in_data_5_ready(in_ready[5]),
        .io_in_data_5_payload({return_dma, return_data}),
        .io_in_data_6_valid(return_valid && return_slice == 6),
        .io_in_data_6_ready(in_ready[6]),
        .io_in_data_6_payload({return_dma, return_data}),
        .io_in_data_7_valid(return_valid && return_slice == 7),
        .io_in_data_7_ready(in_ready[7]),
        .io_in_data_7_payload({return_dma, return_data}),
        .io_in_data_8_valid(return_valid && return_slice == 8),
        .io_in_data_8_ready(in_ready[8]),
        .io_in_data_8_payload({return_dma, return_data}),
        .io_in_data_9_valid(return_valid && return_slice == 9),
        .io_in_data_9_ready(in_ready[9]),
        .io_in_data_9_payload({return_dma, return_data}),
        .io_in_data_10_valid(return_valid && return_slice == 10),
        .io_in_data_10_ready(in_ready[10]),
        .io_in_data_10_payload({return_dma, return_data}),
        .io_in_data_11_valid(return_valid && return_slice == 11),
        .io_in_data_11_ready(in_ready[11]),
        .io_in_data_11_payload({return_dma, return_data}),
        .io_in_data_12_valid(return_valid && return_slice == 12),
        .io_in_data_12_ready(in_ready[12]),
        .io_in_data_12_payload({return_dma, return_data}),
        .io_in_data_13_valid(return_valid && return_slice == 13),
        .io_in_data_13_ready(in_ready[13]),
        .io_in_data_13_payload({return_dma, return_data}),
        .io_in_data_14_valid(return_valid && return_slice == 14),
        .io_in_data_14_ready(in_ready[14]),
        .io_in_data_14_payload({return_dma, return_data}),
        .io_in_data_15_valid(return_valid && return_slice == 15),
        .io_in_data_15_ready(in_ready[15]),
        .io_in_data_15_payload({return_dma, return_data}),
        .io_dma_order_0_valid(order_valid && order_dma == 0),
        .io_dma_order_0_ready(dma_order_ready[0]),
        .io_dma_order_0_payload(order_slice),
        .io_dma_order_1_valid(order_valid && order_dma == 1),
        .io_dma_order_1_ready(dma_order_ready[1]),
        .io_dma_order_1_payload(order_slice),
        .io_dma_order_2_valid(order_valid && order_dma == 2),
        .io_dma_order_2_ready(dma_order_ready[2]),
        .io_dma_order_2_payload(order_slice),
        .io_dma_order_3_valid(order_valid && order_dma == 3),
        .io_dma_order_3_ready(dma_order_ready[3]),
        .io_dma_order_3_payload(order_slice),
        .io_out_data_0_valid(out_valid[0]),
        .io_out_data_0_ready(out_ready[0]),
        .io_out_data_0_payload(out_data[31:0]),
        .io_out_data_1_valid(out_valid[1]),
        .io_out_data_1_ready(out_ready[1]),
        .io_out_data_1_payload(out_data[63:32]),
        .io_out_data_2_valid(out_valid[2]),
        .io_out_data_2_ready(out_ready[2]),
        .io_out_data_2_payload(out_data[95:64]),
        .io_out_data_3_valid(out_valid[3]),
        .io_out_data_3_ready(out_ready[3]),
        .io_out_data_3_payload(out_data[127:96]),
        .clk(clk),
        .resetn(resetn)
    );
endmodule
